basic:
    name: 'MHI Technical Review Site (Legacy)'
    environments:
        production: 'https://www.mhi.co.jp/technology/review'
        staging: ''
        development: ''
    breakpoints:
        - 375
        - 1240
    pages:
        - /
        - /index.html
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 10
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
