basic:
    name: 'MHI - Technical Review Site (Legacy)'
    environments:
        production: 'https://www.mhi.com/jp/technology/review/'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 375
        - 1240
    pages:
        - /
        - /index-62-2
        - /index-62-1
        - /index-61-4
        - /index-61-3
        - /abstract-62-2-20
        - /abstract-62-2-30
        - /abstract-62-2-40
        - /abstract-62-2-50
        - /abstract-62-2-60
        - /abstract-62-2-70
        - /abstract-62-2-80
        - /abstract-62-2-90
        - /abstract-62-2-100
        - /abstract-62-2-110
        - /abstract-62-2-120
        - /abstract-62-2-130
        - /abstract-62-2-140
        - /abstract-62-2-150
        - /abstract-62-2-160
        - /abstract-62-2-170
        - /abstract-62-1-20
        - /abstract-62-1-30
        - /abstract-62-1-40
        - /abstract-62-1-50
        - /abstract-62-1-60
        - /abstract-62-1-70
        - /abstract-62-1-80
        - /abstract-62-1-90
        - /abstract-62-1-100
        - /abstract-62-1-110
        - /abstract-62-1-120
        - /abstract-62-1-130
        - /abstract-62-1-140
        - /abstract-62-1-150
        - /abstract-62-1-160
        - /abstract-62-1-170
        - /abstract-62-1-180
        - /abstract-62-1-190
        - /abstract-62-1-200
        - /abstract-61-4-20
        - /abstract-61-4-30
        - /abstract-61-4-40
        - /abstract-61-4-50
        - /abstract-61-4-60
        - /abstract-61-4-70
        - /abstract-61-4-80
        - /abstract-61-4-90
        - /abstract-61-4-100
        - /abstract-61-4-110
        - /abstract-61-4-120
        - /abstract-61-4-130
        - /abstract-61-4-140
        - /abstract-61-4-150
        - /abstract-61-4-160
        - /abstract-61-4-170
        - /abstract-61-4-180
        - /abstract-61-4-190
        - /abstract-61-4-200
        - /abstract-61-4-210
        - /abstract-61-4-220
        - /abstract-61-4-230
        - /abstract-61-4-240
        - /abstract-61-4-250
        - /abstract-61-4-260
        - /abstract-61-4-270
        - /abstract-61-3-30
        - /abstract-61-3-40
        - /abstract-61-3-50
        - /abstract-61-3-60
        - /abstract-61-3-70
        - /abstract-61-3-80
        - /abstract-61-3-90
        - /abstract-61-3-100
        - /abstract-61-3-110
        - /index-61-2
        - /abstract-61-2-20
        - /abstract-61-2-30
        - /abstract-61-2-40
        - /abstract-61-2-50
        - /abstract-61-2-60
        - /abstract-61-2-80
        - /abstract-61-2-90
        - /abstract-61-1-100
        - /abstract-61-2-110
        - /abstract-61-2-120
        - /abstract-61-2-130
        - /abstract-61-2-140
        - /index-61-1
        - /abstract-61-1-20
        - /abstract-61-1-30
        - /abstract-61-1-40
        - /abstract-61-1-50
        - /abstract-61-1-60
        - /abstract-61-1-70
        - /abstract-61-1-80
        - /abstract-61-1-90
        - /abstract-61-1-110
        - /abstract-61-1-120
        - /abstract-61-1-130
        - /abstract-61-1-140
        - /abstract-61-1-150
        - /abstract-61-1-160
        - /abstract-61-1-170
        - /abstract-61-1-180
        - /abstract-61-1-190
        - /abstract-61-2-150
        - /abstract-61-2-160
        - /index-60-4
        - /abstract-60-4-20
        - /abstract-60-4-30
        - /abstract-60-4-40
        - /abstract-60-4-50
        - /abstract-60-4-60
        - /abstract-60-4-70
        - /abstract-60-4-80
        - /abstract-60-4-90
        - /abstract-60-4-100
        - /abstract-60-4-110
        - /abstract-60-4-120
        - /abstract-60-4-130
        - /index-60-3
        - /abstract-60-3-20
        - /abstract-60-3-30
        - /abstract-60-3-40
        - /abstract-60-3-50
        - /abstract-60-3-60
        - /abstract-60-3-70
        - /abstract-60-3-80
        - /abstract-60-3-90
        - /abstract-60-3-100
        - /abstract-60-3-110
        - /abstract-60-3-120
        - /abstract-60-3-130
        - /abstract-60-3-140
        - /index-60-2
        - /abstract-60-2-20
        - /abstract-60-2-30
        - /abstract-60-2-40
        - /abstract-60-2-50
        - /abstract-60-2-60
        - /abstract-60-2-70
        - /abstract-60-2-80
        - /abstract-60-2-90
        - /abstract-60-2-100
        - /abstract-60-2-110
        - /abstract-60-2-120
        - /abstract-60-2-130
        - /abstract-60-2-140
        - /abstract-60-2-150
        - /abstract-60-2-160
        - /abstract-60-2-170
        - /index-60-1
        - /abstract-60-1-20
        - /abstract-60-1-30
        - /abstract-60-1-40
        - /abstract-60-1-50
        - /abstract-60-1-60
        - /abstract-60-1-70
        - /abstract-60-1-80
        - /abstract-60-1-90
        - /abstract-60-1-100
        - /abstract-60-1-110
        - /abstract-60-1-120
        - /abstract-60-1-130
        - /abstract-60-1-140
        - /abstract-60-1-150
        - /abstract-60-1-160
        - /abstract-60-1-170
        - /abstract-60-1-180
        - /abstract-60-1-190
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
